services:
  mailblogger:
    build: .
    ports:
      - "8080:8080"
    volumes:
      - ./content:/app/content
      - ./config.yaml:/app/config.yaml:ro
      - ./themes:/app/themes
    restart: unless-stopped
